version: "3.1"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - postgresql_db
    links:
      - postgresql_db:postgresql_db
  postgresql_db:
    image: "postgres:14.1-alpine"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
