spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: orderSend
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.kostyanetskiy.orderservice.event.OrderPlaceEvent
        spring.json.trusted.packages: "com.kostyanetskiy.orderservice.event"
      retries: 3
    consumer:
      group-id: orderReceiveGroupId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.kostyanetskiy.orderservice.event.OrderReceiveEvent
        spring.json.trusted.packages: "com.kostyanetskiy.orderservice.event"
  application:
    name: order-service
server:
  port: 8082

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka

jwt_secret: ORDERSERVICESECRET
