version: '3.1'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: delivery-service
    build:
      context: ""
    image: delivery-service
    depends_on:
      - db
    ports:
      - 8083:8080
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5434
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local

