eureka:
  client:
    serviceUrl.defaultZone: http://eureka:password@discovery-server:8761/eureka
spring:
  application:
    name: api-gareaway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/api/v1/order/**,/api/v1/auth/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
          - Path=/api/v1/courier/**,/api/v1/delivery/**
          filters:
            - RewritePath=/delivery-service/(?<path>.*), /$\{path}
        - id: discovery-service
          uri: http://eureka:password@discovery-server:8761
          predicates:
          - Path=/eureka/web
          filters:
          - SetPath=/
        - id: discovery-service-static
          uri: http://eureka:password@discovery-server:8761
          predicates:
          - Path=/eureka/**
        - id: openapi
          uri: http://localhost:8181
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

logging.level.root: INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
logging.level.org.springframework.cloud.gateway: TRACE

server:
  port: 8080
