eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gareaway
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/v1/order/**,/api/v1/auth/**
      - id: delivery-service
        uri: lb://delivery-service
        predicates:
        - Path=/api/v1/courier/**,/api/v1/delivery/**
      - id: discovery-service
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/
      - id: discovery-service-static
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/**


logging.level.root: INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
logging.level.org.springframework.cloud.gateway: TRACE
server:
  port: 8181
